# Generated by Django 5.0.9 on 2024-10-10 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Klass',
                'verbose_name_plural': 'Klasslar',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel/')),
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('period_amount', models.IntegerField(help_text='Muddatning miqdori (1, 4, 5 ...)')),
                ('period_unit', models.CharField(help_text='Muddatning birligi (kun, hafta, oy ...)', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.hotel')),
                ('travel_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.class')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
            },
        ),
    ]
